language: node_js
node_js:
- "lts/*"
branches:
  only:
  - master
  - develop
script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build:prod; else npm run build:dev; fi
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  repo: SLIOI/slioi.github.io
  target-branch: master
  verbose: true
  on:
    repo: SLIOI/website
    branch: master
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    repo: SLIOI/website
    branch: develop