language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - "node_modules"
script: npm build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  repo: SLIOI/slioi.github.io
  target-branch: master
  verbose: true
  on:
    branch: master